# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
#
trigger:
  - master

pool:
  vmImage: ubuntu-latest
  variables:
    CC: gcc-11
    CXX: g++-11
    CXXFLAGS: -lstdc++fs

steps:
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        # Write your commands here
        
        echo 'install -> gcc-11'
        sudo apt-get upgrade -y -f build-essential g++ gcc gfortran r-base-dev
        export PATH="/usr/bin/gcc:$PATH"
        which gcc
        ls -all
        gcc -v

  - task: run-cmake@0
    inputs:
      cmakeListsOrSettingsJson: 'CMakeListsTxtBasic'
      cmakeListsTxtPath: './CMakeLists.txt'
      cmakeGenerator: 'Ninja'
      buildDirectory: './build'
      buildWithCMakeArgs: '-DCMAKE_CXX_COMPILER=g++-11'
