# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
#
trigger:
  - master

pool:
  vmImage: ubuntu-latest
  variables:
    CC: gcc-11
    CXX: g++-11
    CXXFLAGS: -lstdc++fs

steps:
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        # Write your commands here
        
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt-get update
        echo 'install -> gcc-11'
        sudo apt-get install g++-11 gcc-11
        echo 'upgrade -> '
        sudo apt-get upgrade -y -f build-essential gfortran r-base-dev
        export PATH="/usr/bin/gcc-11:$PATH"
        which gcc-11
        ls -all
        gcc-11 -v

  - task: run-cmake@0
    inputs:
      cmakeListsOrSettingsJson: 'CMakeListsTxtBasic'
      cmakeListsTxtPath: './CMakeLists.txt'
      cmakeGenerator: 'Ninja'
      buildDirectory: './build'
      buildWithCMakeArgs: '-DCMAKE_C_COMPILER=/usr/bin/gcc-11 -DCMAKE_CXX_COMPILER=/usr/bin/g++-11'
