# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
#
trigger:
  - master

pool:
  vmImage: ubuntu-22.04
  variables:
    CC: gcc-11
    CXX: g++-11
    CXXFLAGS: -lstdc++fs
steps:
  - task: run-cmake@0
    displayName: Run Cmake -> build ninja
    inputs:
      cmakeListsOrSettingsJson: 'CMakeListsTxtBasic'
      cmakeListsTxtPath: './CMakeLists.txt'
      cmakeBuildType: 'Debug'
      cmakeGenerator: 'Ninja'
      buildDirectory: './build'
      buildWithCMakeArgs: '--coverage'