# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
#
trigger:
  - master

pool:
  vmImage: ubuntu-latest

steps:
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        # Write your commands here
        
        echo 'Hello world'
        ls -all
        gcc -v
        sudo apt-get install -y gcc-11

  - task: run-cmake@0
    inputs:
      cmakeListsOrSettingsJson: 'CMakeListsTxtBasic'
      cmakeListsTxtPath: './CMakeLists.txt'
      cmakeGenerator: 'Ninja'
      buildDirectory: './build'